### ISSUE TITLE
Regarding Computation of Class Embeddings

### ISSUE THREAD

**Issue by saurabhsharma1993** [LisaAnne/ECCV2016#7]
Hi Lisa, 

Thanx a lot for your code. I'm running into a problem while using your code. For computing the class embeddings, one needs to run the description model. The steps in your README direct one to use the make_class_embeddings.sh file, which runs the following code :

python utils/extract_train_val.py --model_name $model \
                       --LM_net $word_net \
                       --dataset_name $dataset_name \
                       --split_name $split_name \
                       --vocab $vocab \
                       --image_net $image_net \
                       --size_input_feature $size_input_feature \
                       --prev_word_restriction \
                       --precomputed_h5 data/CUB_feature_010517.p 

There is no such utils/extract_train_val.py file in the repo. Moreover, this file isn't generated by the build_models.sh code either. So I'm confused, and am unable to use the code. Would be glad if you can clear this doubt.

Regards,
Saurabh

**Comment by LisaAnne** [comment]
Hi --

I tried to clean this code a while ago and moved some things around; I
found the file you are looking for in my deprecated branch:

https://github.com/LisaAnne/ECCV2016/blob/deprecated/examples/ECCV2016/extract_train_val.py

Sorry about that!
